apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  minReplicas: 2
  maxReplicas: 50
  metrics:
  - type: ContainerResource
    containerResource:  
      container: SERVICE_NAME
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40